# Generated by Django 5.1.4 on 2025-03-30 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('density', models.FloatField(help_text='Density in g/cm³')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_thickness', models.FloatField(default=0.5, help_text='Minimum thickness in mm')),
                ('max_thickness', models.FloatField(default=20.0, help_text='Maximum thickness in mm')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
            ],
        ),
        migrations.CreateModel(
            name='ShapeTemplate',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('svg_path', models.TextField(help_text='SVG path data for rendering')),
            ],
        ),
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_factor', models.FloatField(help_text='Multiplier for the base price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coatings/')),
                ('compatible_materials', models.ManyToManyField(to='metal_api.material')),
            ],
        ),
        migrations.CreateModel(
            name='MetalDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Quote'), ('quoted', 'Quote Provided'), ('accepted', 'Quote Accepted'), ('rejected', 'Quote Rejected'), ('in_production', 'In Production'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('shape_dimensions', models.JSONField(help_text='JSON object with dimensions')),
                ('cutouts', models.JSONField(default=list, help_text='JSON array of cutout coordinates')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_production_time', models.PositiveIntegerField(blank=True, help_text='Estimated production time in days', null=True)),
                ('notes', models.TextField(blank=True)),
                ('coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metal_api.coating')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metal_api.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metal_api.material')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shape_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metal_api.shapetemplate')),
            ],
        ),
    ]
