# Generated by Django 5.1.4 on 2025-02-26 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Price Quoted'), ('accepted', 'Quote Accepted'), ('rejected', 'Quote Rejected'), ('in_production', 'In Production'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('material', models.CharField(choices=[('steel', 'Steel'), ('aluminum', 'Aluminum'), ('copper', 'Copper'), ('brass', 'Brass')], max_length=20)),
                ('thickness', models.FloatField()),
                ('finish', models.CharField(choices=[('none', 'None (Raw)'), ('polished', 'Polished'), ('brushed', 'Brushed'), ('painted', 'Painted'), ('powder-coated', 'Powder Coated')], max_length=20)),
                ('shape', models.CharField(max_length=20)),
                ('custom_path', models.TextField(blank=True)),
                ('features_json', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('svg_preview', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_notes', models.TextField(blank=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_designs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_production_days', models.IntegerField(default=7)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='metal_api.metaldesign')),
            ],
        ),
    ]
